### ISSUE TITLE
How can I use DnsClient to get all global catalogs DCs ?

### ISSUE THREAD

**Issue by idang100102** [MichaCo/DnsClient.NET.Samples#1]
Hi,

How can I use DnsClient to get all global catalogs DCs ?
Something like PowerShell's: nslookup gc._msdcs.mydomain.com

Thanks

**Comment by MichaConrad** [comment]
I guess you are talking about domain controller's global catalogs?
That's probably the wrong location for such a question, this has nothing to do with this library.

Anyways, I simply googled it and [this article](https://www.oreilly.com/library/view/active-directory-cookbook/0596004648/ch03s22.html) might help?

**Comment by idang100102** [comment]
Right, but I am looking for a C#/C++ library, and not a powershell command.
Do you know any?
Thanks

**Comment by MichaConrad** [comment]
The article describes all the DNS queries you have to run, like a query against `_ldap._tcp.<DomainDNSName>` with query type being `SRV` and such...
That's what you can use DnsClient for in C#...

**Comment by idang100102** [comment]
Sorry to bother... I look for a non-ldap way to get the GCs, and prefer a code based query with no use of powershell.
Are you sure DnsClient has no capability to distinguish between a GC-DC and a non-GC-DC ?
Thanks a lot.
